"""
Django settings for moma_ws project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0%jah4bv$9)me$(x+#t64*lm0oy33o+3c#2&3k70&oowz84vvl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['0.0.0.0', '127.0.0.1', '104.248.56.35', '206.189.252.183', 'localhost']


# Application definition

INSTALLED_APPS = [
    'artmonitors.apps.ArtmonitorsConfig',
    'personal.apps.PersonalConfig',
    'wordcount.apps.WordcountConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'moma_ws.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moma_ws.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Timekeeping

LAST_UPDATE_DATE = datetime.date.today()
while LAST_UPDATE_DATE.weekday() != 0:
    LAST_UPDATE_DATE -= datetime.timedelta(days=1)


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/2.1/howto/static-files/
#
# STATIC_URL = '/static/'  # os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = BASE_DIR + "/static/" # os.path.join(BASE_DIR, 'static')
# # STATICFILES_DIRS = (os.path.join(STATIC_ROOT), )
# DJANGO_STATIC_SAVE_PREFIX = os.path.join(os.path.dirname(os.getcwd()),)
#
# # Media files for artmonitors
#
# MEDIA_ROOT = STATIC_ROOT + "media/" # os.path.join(STATIC_ROOT, 'media/')  # 'static/media/'
# MEDIA_URL = '/static/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR + "/static/"
# STATICFILES_DIRS = (os.path.join('static'), )
DJANGO_STATIC_SAVE_PREFIX = os.path.join(os.path.dirname(os.getcwd()),)

# Media files for artmonitors

# MEDIA_ROOT = '/Users/Birdy/Documents/Programming/HTML/app/Webservice/moma_ws/static/media/'
MEDIA_ROOT = STATIC_ROOT + "media/"
# os.path.join(os.getcwd(), os.pardir, 'static', 'media')
# MEDIA_URL = '/Users/Birdy/Documents/Programming/HTML/app/Webservice/moma_ws/static/media/' # 'static/media/'
MEDIA_URL = '/static/media/'
FILE_UPLOAD_PERMISSIONS = 0o644

